[features]
seeds = false

[programs.localnet]
campaign_treasury_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
campaign_treasury_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.testnet]
campaign_treasury_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "artifacts/mpl_token_metadata.so"

[provider]
cluster = "localnet"
wallet = "keys/localnet.json"

[workspace]
members = [
  "programs/campaign-treasury-manager",
]

[scripts]
test = "./scripts/test-program.sh"